//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RecordID { get; set; }
        public int Cust_No { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> Size { get; set; }
        public Nullable<decimal> Acquisition { get; set; }
        public string Offer { get; set; }
        public Nullable<int> Season { get; set; }
    }
}
